### ISSUE TITLE
transform result accuracy

### ISSUE THREAD

**Issue by zbml** [wroge/wgs84#1]
Here's my code
```go
type spheroid struct {
	a, fi float64
}

func (s spheroid) A() float64 {
	return s.a
}

func (s spheroid) Fi() float64 {
	return s.fi
}

func main() {
	test := wgs84.Datum{
		Spheroid: spheroid{
			a:  6378137,
			fi: 298.257222101,
		},
		Area: wgs84.AreaFunc(func(lon, lat float64) bool {
			if lon < 118.5 || lon > 121.5 || lat < 24.43 || lat > 53.33 {
				return false
			}
			return true
		}),
	}

	proj := test.TransverseMercator(120, 0, 1, 500000, 0)

	epsg := wgs84.EPSG()
	epsg.Add(4549, proj)

	transform := wgs84.Transform(epsg.Code(4549), wgs84.LonLat())
	f1, f2, f3 := transform(478077, 4025869, 0)
	fmt.Println(f1, f2, f3)

}
```

wkt for epsg:4549
```
PROJCS["CGCS2000 / 3-degree Gauss-Kruger CM 120E",
    GEOGCS["China Geodetic Coordinate System 2000",
        DATUM["China_2000",
            SPHEROID["CGCS2000",6378137,298.257222101,
                AUTHORITY["EPSG","1024"]],
            AUTHORITY["EPSG","1043"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4490"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",120],
    PARAMETER["scale_factor",1],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AUTHORITY["EPSG","4549"]]
```

With my code I got result is [119.75572865201768, 36.36317346481494, -3.6767683923244476e-05]
But What I got form epsg.io was [119.7557287, 36.3631738], and from gdaltransform was [119.755728654111, 36.3631737608256, 0]

So I am wandering what makes these differences? Is there any problems?

**Comment by wroge** [comment]
Hi @zbml , I'm sorry for being so late in replying.
The differences come from the fact that the algorithms round differently in the intermediate steps. Also, the float64 data type used has some [inaccuracy](https://stackoverflow.com/questions/21895756/why-are-floating-point-numbers-inaccurate) because the number is not stored in the decimal system.
You could eliminate this inaccuracy by using [this](github.com/shopspring/decimal) decimal-package for example, but in general this accuracy is not necessary for most applications.

Does this answer the question?

**Comment by wroge** [comment]
If the first 6 decimal places are equal, the precision is less than 10 cm.
It is also important to understand that most algorithms are only approximations that try to represent reality in the most accurate, but also the simplest way.

<img width="711" alt="Bildschirmfoto 2022-04-03 um 09 35 20" src="https://user-images.githubusercontent.com/44040384/161416833-cb2756d9-3a44-4273-913e-f08d77f1d91b.png">

[Source](https://wiki.openstreetmap.org/wiki/Precision_of_coordinates)

**Comment by wroge** [comment]
I have done a rewrite for v2 (currently in alpha stage). It seems you were right and there were some accuracy issues that are now fixed.

```go
package main

import (
	"fmt"

	"github.com/wroge/wgs84/v2"
)

func main() {
	transform := wgs84.Transform(wgs84.EPSG(4549), wgs84.EPSG(4326)).Round(10)

	lon, lat, _ := transform(478077, 4025869, 0)

	fmt.Println(lon, lat)
	// 119.7557286545 36.3631737806

	// echo 478077 4025869 | cs2cs +init=epsg:4549 +to +init=epsg:4326 -d 10
	// 119.7557286541 36.3631737608

	// epsg.io
	// 119.7557287 36.3631738
}
```

**Comment by zbml** [comment]
Really appreciate this update
I think the accuracy is ok now
