### ISSUE TITLE
geometric altitude to wgs84 altitude

### ISSUE THREAD

**Issue by tommynanny** [wroge/wgs84#2]
Hi, I am very new to gis, but if I have lat, long, and a geometric altitude (above mean sea level), can I use this package to convert the geometric altitude to the wgs84 altitude?

**Comment by lgln-mw** [comment]
If you only want to calculate the different height at one point with two different geodetic datums (with different ellipsoid), you can do that with this package.
However, there are different vertical datums that you should think about beforehand. These are often not based on an ellipsoid, but on a geoid.

**Comment by wroge** [comment]
If you only want to calculate the different height at one point with two different geodetic datums, you can do that with this package.
However, there are different vertical datums that you should think about beforehand. These are often not based on an ellipsoid, but on a geoid.
